/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab4;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class BitmapTest {



}
